// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/approval/action.proto

package approval

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 查询记录的请求
type ActionQueryRequest struct {
	Offset               int64        `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64        `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Workflow             string       `protobuf:"bytes,3,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Task                 string       `protobuf:"bytes,4,opt,name=task,proto3" json:"task,omitempty"`
	Operator             string       `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	State                ActionStatus `protobuf:"varint,6,opt,name=state,proto3,enum=approval.ActionStatus" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ActionQueryRequest) Reset()         { *m = ActionQueryRequest{} }
func (m *ActionQueryRequest) String() string { return proto.CompactTextString(m) }
func (*ActionQueryRequest) ProtoMessage()    {}
func (*ActionQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9335c6862921c8b7, []int{0}
}

func (m *ActionQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionQueryRequest.Unmarshal(m, b)
}
func (m *ActionQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionQueryRequest.Marshal(b, m, deterministic)
}
func (m *ActionQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionQueryRequest.Merge(m, src)
}
func (m *ActionQueryRequest) XXX_Size() int {
	return xxx_messageInfo_ActionQueryRequest.Size(m)
}
func (m *ActionQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionQueryRequest proto.InternalMessageInfo

func (m *ActionQueryRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ActionQueryRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ActionQueryRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *ActionQueryRequest) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

func (m *ActionQueryRequest) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ActionQueryRequest) GetState() ActionStatus {
	if m != nil {
		return m.State
	}
	return ActionStatus_ACTION_STATUS_INVALID
}

// 查询记录的回复
type ActionQueryResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*ActionEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ActionQueryResponse) Reset()         { *m = ActionQueryResponse{} }
func (m *ActionQueryResponse) String() string { return proto.CompactTextString(m) }
func (*ActionQueryResponse) ProtoMessage()    {}
func (*ActionQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9335c6862921c8b7, []int{1}
}

func (m *ActionQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionQueryResponse.Unmarshal(m, b)
}
func (m *ActionQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionQueryResponse.Marshal(b, m, deterministic)
}
func (m *ActionQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionQueryResponse.Merge(m, src)
}
func (m *ActionQueryResponse) XXX_Size() int {
	return xxx_messageInfo_ActionQueryResponse.Size(m)
}
func (m *ActionQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActionQueryResponse proto.InternalMessageInfo

func (m *ActionQueryResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ActionQueryResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ActionQueryResponse) GetEntity() []*ActionEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*ActionQueryRequest)(nil), "approval.ActionQueryRequest")
	proto.RegisterType((*ActionQueryResponse)(nil), "approval.ActionQueryResponse")
}

func init() {
	proto.RegisterFile("proto/approval/action.proto", fileDescriptor_9335c6862921c8b7)
}

var fileDescriptor_9335c6862921c8b7 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x8d, 0x5d, 0xc3, 0x3c, 0x03, 0x91, 0xa3, 0x8c, 0x30, 0x15, 0xca, 0xae, 0x7a, 0x21,
	0x1d, 0xd4, 0x27, 0xf0, 0x42, 0xaf, 0x35, 0x3e, 0x41, 0x9c, 0x29, 0x8e, 0x95, 0x9e, 0x9a, 0x9c,
	0x3a, 0xf6, 0x00, 0xbe, 0x95, 0x0f, 0x27, 0x4b, 0x5a, 0xff, 0x4c, 0xbc, 0xeb, 0xf7, 0x9d, 0x5f,
	0xc2, 0xef, 0x34, 0x70, 0xde, 0x3a, 0x62, 0x5a, 0x98, 0xb6, 0x75, 0xf4, 0x66, 0xea, 0x85, 0x59,
	0xf2, 0x8a, 0x9a, 0x22, 0xb4, 0x38, 0x1e, 0xea, 0xd9, 0x3e, 0xe6, 0x5f, 0x8c, 0xb3, 0xcf, 0x11,
	0x9b, 0x7f, 0x08, 0xc0, 0x9b, 0x70, 0xee, 0xa1, 0xb3, 0x6e, 0xab, 0xed, 0x6b, 0x67, 0x3d, 0xe3,
	0x14, 0x24, 0x55, 0x95, 0xb7, 0xac, 0x44, 0x26, 0xf2, 0x44, 0xf7, 0x09, 0xcf, 0x20, 0x5d, 0x52,
	0xd7, 0xb0, 0x3a, 0x0c, 0x75, 0x0c, 0x38, 0x83, 0xf1, 0x86, 0xdc, 0xba, 0xaa, 0x69, 0xa3, 0x92,
	0x4c, 0xe4, 0x47, 0xfa, 0x2b, 0x23, 0xc2, 0x88, 0x8d, 0x5f, 0xab, 0x51, 0xe8, 0xc3, 0xf7, 0x8e,
	0xa7, 0xd6, 0x3a, 0xc3, 0xe4, 0x54, 0x1a, 0xf9, 0x21, 0xe3, 0x15, 0xa4, 0x9e, 0x0d, 0x5b, 0x25,
	0x33, 0x91, 0x1f, 0x97, 0xd3, 0x62, 0xf0, 0x2e, 0xa2, 0xe6, 0x23, 0x1b, 0xee, 0xbc, 0x8e, 0xd0,
	0xfc, 0x5d, 0xc0, 0xe9, 0x2f, 0x7d, 0xdf, 0x52, 0xe3, 0x2d, 0xe6, 0x20, 0x7d, 0x00, 0x83, 0xff,
	0xa4, 0x3c, 0xf9, 0xbe, 0xa6, 0xbf, 0xa0, 0x9f, 0xef, 0x36, 0x62, 0x62, 0x53, 0x87, 0x8d, 0x46,
	0x3a, 0x06, 0x2c, 0x40, 0xda, 0x86, 0x57, 0xbc, 0x55, 0x49, 0x96, 0xe4, 0x93, 0xbf, 0x1a, 0xb7,
	0x61, 0xaa, 0x7b, 0xaa, 0xbc, 0x07, 0x19, 0x7b, 0xbc, 0x83, 0x34, 0xa8, 0xe0, 0xc5, 0xfe, 0x91,
	0x9f, 0x3f, 0x78, 0x76, 0xf9, 0xcf, 0x34, 0xfa, 0xcf, 0x0f, 0x9e, 0x64, 0x78, 0x9f, 0xeb, 0xcf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0xe9, 0x93, 0xb3, 0xe5, 0x01, 0x00, 0x00,
}
