// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/approval/action.proto

package approval

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Action service

type ActionService interface {
	// 查询
	Query(ctx context.Context, in *ActionQueryRequest, opts ...client.CallOption) (*ActionQueryResponse, error)
}

type actionService struct {
	c    client.Client
	name string
}

func NewActionService(name string, c client.Client) ActionService {
	return &actionService{
		c:    c,
		name: name,
	}
}

func (c *actionService) Query(ctx context.Context, in *ActionQueryRequest, opts ...client.CallOption) (*ActionQueryResponse, error) {
	req := c.c.NewRequest(c.name, "Action.Query", in)
	out := new(ActionQueryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Action service

type ActionHandler interface {
	// 查询
	Query(context.Context, *ActionQueryRequest, *ActionQueryResponse) error
}

func RegisterActionHandler(s server.Server, hdlr ActionHandler, opts ...server.HandlerOption) error {
	type action interface {
		Query(ctx context.Context, in *ActionQueryRequest, out *ActionQueryResponse) error
	}
	type Action struct {
		action
	}
	h := &actionHandler{hdlr}
	return s.Handle(s.NewHandler(&Action{h}, opts...))
}

type actionHandler struct {
	ActionHandler
}

func (h *actionHandler) Query(ctx context.Context, in *ActionQueryRequest, out *ActionQueryResponse) error {
	return h.ActionHandler.Query(ctx, in, out)
}
