// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/approval/operator.proto

package approval

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 加入的请求
type OperatorJoinRequest struct {
	Operator             string   `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Workflow             string   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorJoinRequest) Reset()         { *m = OperatorJoinRequest{} }
func (m *OperatorJoinRequest) String() string { return proto.CompactTextString(m) }
func (*OperatorJoinRequest) ProtoMessage()    {}
func (*OperatorJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10682c9168bd77ed, []int{0}
}

func (m *OperatorJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorJoinRequest.Unmarshal(m, b)
}
func (m *OperatorJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorJoinRequest.Marshal(b, m, deterministic)
}
func (m *OperatorJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorJoinRequest.Merge(m, src)
}
func (m *OperatorJoinRequest) XXX_Size() int {
	return xxx_messageInfo_OperatorJoinRequest.Size(m)
}
func (m *OperatorJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorJoinRequest proto.InternalMessageInfo

func (m *OperatorJoinRequest) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *OperatorJoinRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

// 离开的请求
type OperatorLeaveRequest struct {
	Operator             string   `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Workflow             string   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorLeaveRequest) Reset()         { *m = OperatorLeaveRequest{} }
func (m *OperatorLeaveRequest) String() string { return proto.CompactTextString(m) }
func (*OperatorLeaveRequest) ProtoMessage()    {}
func (*OperatorLeaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10682c9168bd77ed, []int{1}
}

func (m *OperatorLeaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorLeaveRequest.Unmarshal(m, b)
}
func (m *OperatorLeaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorLeaveRequest.Marshal(b, m, deterministic)
}
func (m *OperatorLeaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorLeaveRequest.Merge(m, src)
}
func (m *OperatorLeaveRequest) XXX_Size() int {
	return xxx_messageInfo_OperatorLeaveRequest.Size(m)
}
func (m *OperatorLeaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorLeaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorLeaveRequest proto.InternalMessageInfo

func (m *OperatorLeaveRequest) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *OperatorLeaveRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

// 列举的请求
type OperatorListRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Workflow             string   `protobuf:"bytes,3,opt,name=workflow,proto3" json:"workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorListRequest) Reset()         { *m = OperatorListRequest{} }
func (m *OperatorListRequest) String() string { return proto.CompactTextString(m) }
func (*OperatorListRequest) ProtoMessage()    {}
func (*OperatorListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10682c9168bd77ed, []int{2}
}

func (m *OperatorListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorListRequest.Unmarshal(m, b)
}
func (m *OperatorListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorListRequest.Marshal(b, m, deterministic)
}
func (m *OperatorListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorListRequest.Merge(m, src)
}
func (m *OperatorListRequest) XXX_Size() int {
	return xxx_messageInfo_OperatorListRequest.Size(m)
}
func (m *OperatorListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorListRequest proto.InternalMessageInfo

func (m *OperatorListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *OperatorListRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *OperatorListRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

// 列举的回复
type OperatorListResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []string `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorListResponse) Reset()         { *m = OperatorListResponse{} }
func (m *OperatorListResponse) String() string { return proto.CompactTextString(m) }
func (*OperatorListResponse) ProtoMessage()    {}
func (*OperatorListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10682c9168bd77ed, []int{3}
}

func (m *OperatorListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorListResponse.Unmarshal(m, b)
}
func (m *OperatorListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorListResponse.Marshal(b, m, deterministic)
}
func (m *OperatorListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorListResponse.Merge(m, src)
}
func (m *OperatorListResponse) XXX_Size() int {
	return xxx_messageInfo_OperatorListResponse.Size(m)
}
func (m *OperatorListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorListResponse proto.InternalMessageInfo

func (m *OperatorListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *OperatorListResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OperatorListResponse) GetEntity() []string {
	if m != nil {
		return m.Entity
	}
	return nil
}

// 过滤的请求
type OperatorFilterRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorFilterRequest) Reset()         { *m = OperatorFilterRequest{} }
func (m *OperatorFilterRequest) String() string { return proto.CompactTextString(m) }
func (*OperatorFilterRequest) ProtoMessage()    {}
func (*OperatorFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10682c9168bd77ed, []int{4}
}

func (m *OperatorFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorFilterRequest.Unmarshal(m, b)
}
func (m *OperatorFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorFilterRequest.Marshal(b, m, deterministic)
}
func (m *OperatorFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorFilterRequest.Merge(m, src)
}
func (m *OperatorFilterRequest) XXX_Size() int {
	return xxx_messageInfo_OperatorFilterRequest.Size(m)
}
func (m *OperatorFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorFilterRequest proto.InternalMessageInfo

func (m *OperatorFilterRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *OperatorFilterRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *OperatorFilterRequest) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

// 过滤的回复
type OperatorFilterResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []string `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorFilterResponse) Reset()         { *m = OperatorFilterResponse{} }
func (m *OperatorFilterResponse) String() string { return proto.CompactTextString(m) }
func (*OperatorFilterResponse) ProtoMessage()    {}
func (*OperatorFilterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10682c9168bd77ed, []int{5}
}

func (m *OperatorFilterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorFilterResponse.Unmarshal(m, b)
}
func (m *OperatorFilterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorFilterResponse.Marshal(b, m, deterministic)
}
func (m *OperatorFilterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorFilterResponse.Merge(m, src)
}
func (m *OperatorFilterResponse) XXX_Size() int {
	return xxx_messageInfo_OperatorFilterResponse.Size(m)
}
func (m *OperatorFilterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorFilterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorFilterResponse proto.InternalMessageInfo

func (m *OperatorFilterResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *OperatorFilterResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OperatorFilterResponse) GetEntity() []string {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*OperatorJoinRequest)(nil), "approval.OperatorJoinRequest")
	proto.RegisterType((*OperatorLeaveRequest)(nil), "approval.OperatorLeaveRequest")
	proto.RegisterType((*OperatorListRequest)(nil), "approval.OperatorListRequest")
	proto.RegisterType((*OperatorListResponse)(nil), "approval.OperatorListResponse")
	proto.RegisterType((*OperatorFilterRequest)(nil), "approval.OperatorFilterRequest")
	proto.RegisterType((*OperatorFilterResponse)(nil), "approval.OperatorFilterResponse")
}

func init() {
	proto.RegisterFile("proto/approval/operator.proto", fileDescriptor_10682c9168bd77ed)
}

var fileDescriptor_10682c9168bd77ed = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xdf, 0x4e, 0x32, 0x31,
	0x10, 0xc5, 0x3f, 0x58, 0xd8, 0xc0, 0x7c, 0x37, 0xa6, 0x22, 0x92, 0x35, 0x20, 0xd9, 0x2b, 0xae,
	0x20, 0xc1, 0x17, 0x30, 0x5c, 0x68, 0x62, 0x40, 0x93, 0xfa, 0x00, 0xa6, 0x6a, 0x89, 0x1b, 0x36,
	0x9d, 0xda, 0x0e, 0x10, 0xdf, 0xc8, 0xc7, 0x34, 0xdb, 0xdd, 0xf2, 0x1f, 0x2f, 0x34, 0x5e, 0x9e,
	0x9e, 0xd9, 0xdf, 0x99, 0x4e, 0x67, 0xa1, 0xad, 0x0d, 0x12, 0x0e, 0x84, 0xd6, 0x06, 0x17, 0x22,
	0x1d, 0xa0, 0x96, 0x46, 0x10, 0x9a, 0xbe, 0x3b, 0x67, 0x35, 0x6f, 0x44, 0x17, 0x3b, 0x85, 0xf6,
	0x4d, 0x18, 0xf9, 0x9a, 0x97, 0xc5, 0x13, 0x38, 0x7d, 0x28, 0x3e, 0xbc, 0xc3, 0x44, 0x71, 0xf9,
	0x3e, 0x97, 0x96, 0x58, 0x04, 0x35, 0xcf, 0x6b, 0x95, 0xba, 0xa5, 0x5e, 0x9d, 0xaf, 0x74, 0xe6,
	0x2d, 0xd1, 0xcc, 0xa6, 0x29, 0x2e, 0x5b, 0xe5, 0xdc, 0xf3, 0x3a, 0xbe, 0x87, 0x86, 0xc7, 0x8d,
	0xa5, 0x58, 0xc8, 0xdf, 0xf2, 0x9e, 0xd6, 0xed, 0x8d, 0x13, 0x4b, 0x1e, 0xd7, 0x84, 0x10, 0xa7,
	0x53, 0x2b, 0xc9, 0xc1, 0x02, 0x5e, 0x28, 0xd6, 0x80, 0xea, 0x0b, 0xce, 0x15, 0x39, 0x4e, 0xc0,
	0x73, 0xb1, 0x15, 0x10, 0xec, 0x04, 0xa8, 0x8d, 0x86, 0x5d, 0x80, 0xd5, 0xa8, 0xac, 0x64, 0x3d,
	0x08, 0x2d, 0x09, 0x9a, 0x5b, 0x97, 0xf0, 0x7f, 0x78, 0xd2, 0xf7, 0xf3, 0xeb, 0x3f, 0xba, 0x73,
	0x5e, 0xf8, 0x59, 0x26, 0x21, 0x89, 0xd4, 0x65, 0x56, 0x78, 0x2e, 0xb2, 0x0e, 0xa5, 0xa2, 0x84,
	0x3e, 0x5a, 0x41, 0x37, 0xe8, 0xd5, 0x79, 0xa1, 0x62, 0x01, 0x67, 0x3e, 0xef, 0x26, 0x49, 0x49,
	0x9a, 0x1f, 0x5f, 0x69, 0x35, 0xcf, 0x60, 0x7b, 0x9e, 0xb1, 0x86, 0xe6, 0x6e, 0xc4, 0xdf, 0x5e,
	0x6a, 0xf8, 0x59, 0x86, 0x9a, 0x8f, 0x64, 0xd7, 0x50, 0xc9, 0x36, 0x89, 0xb5, 0xd7, 0xf0, 0x03,
	0x1b, 0x16, 0x9d, 0xaf, 0xed, 0x51, 0x2a, 0xd4, 0xcc, 0x37, 0x19, 0xff, 0x63, 0x23, 0xa8, 0xba,
	0xe5, 0x61, 0x9d, 0x7d, 0xc4, 0xe6, 0x56, 0x7d, 0xc7, 0xb8, 0x85, 0x4a, 0xf6, 0x9e, 0x87, 0xba,
	0xd8, 0x58, 0xa4, 0xa8, 0x73, 0xcc, 0x5e, 0x81, 0x26, 0x10, 0xe6, 0x53, 0x64, 0x97, 0xfb, 0xb5,
	0x5b, 0x4f, 0x18, 0x75, 0x8f, 0x17, 0x78, 0xdc, 0x73, 0xe8, 0x7e, 0xbb, 0xab, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xed, 0x78, 0x70, 0xe2, 0xbe, 0x03, 0x00, 0x00,
}
