// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/approval/operator.proto

package approval

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 加入的请求
type OperatorJoinRequest struct {
	Operator             string   `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Workflow             string   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorJoinRequest) Reset()         { *m = OperatorJoinRequest{} }
func (m *OperatorJoinRequest) String() string { return proto.CompactTextString(m) }
func (*OperatorJoinRequest) ProtoMessage()    {}
func (*OperatorJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10682c9168bd77ed, []int{0}
}

func (m *OperatorJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorJoinRequest.Unmarshal(m, b)
}
func (m *OperatorJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorJoinRequest.Marshal(b, m, deterministic)
}
func (m *OperatorJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorJoinRequest.Merge(m, src)
}
func (m *OperatorJoinRequest) XXX_Size() int {
	return xxx_messageInfo_OperatorJoinRequest.Size(m)
}
func (m *OperatorJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorJoinRequest proto.InternalMessageInfo

func (m *OperatorJoinRequest) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *OperatorJoinRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

// 离开的请求
type OperatorLeaveRequest struct {
	Operator             string   `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Workflow             string   `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorLeaveRequest) Reset()         { *m = OperatorLeaveRequest{} }
func (m *OperatorLeaveRequest) String() string { return proto.CompactTextString(m) }
func (*OperatorLeaveRequest) ProtoMessage()    {}
func (*OperatorLeaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10682c9168bd77ed, []int{1}
}

func (m *OperatorLeaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorLeaveRequest.Unmarshal(m, b)
}
func (m *OperatorLeaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorLeaveRequest.Marshal(b, m, deterministic)
}
func (m *OperatorLeaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorLeaveRequest.Merge(m, src)
}
func (m *OperatorLeaveRequest) XXX_Size() int {
	return xxx_messageInfo_OperatorLeaveRequest.Size(m)
}
func (m *OperatorLeaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorLeaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorLeaveRequest proto.InternalMessageInfo

func (m *OperatorLeaveRequest) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *OperatorLeaveRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func init() {
	proto.RegisterType((*OperatorJoinRequest)(nil), "approval.OperatorJoinRequest")
	proto.RegisterType((*OperatorLeaveRequest)(nil), "approval.OperatorLeaveRequest")
}

func init() {
	proto.RegisterFile("proto/approval/operator.proto", fileDescriptor_10682c9168bd77ed)
}

var fileDescriptor_10682c9168bd77ed = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2c, 0x28, 0x28, 0xca, 0x2f, 0x4b, 0xcc, 0xd1, 0xcf, 0x2f, 0x48, 0x2d, 0x4a,
	0x2c, 0xc9, 0x2f, 0xd2, 0x03, 0x8b, 0x0b, 0x71, 0xc0, 0x24, 0xa4, 0xa4, 0xd1, 0x14, 0x16, 0x67,
	0x24, 0x16, 0xa5, 0xa6, 0x40, 0x94, 0x29, 0xf9, 0x72, 0x09, 0xfb, 0x43, 0x35, 0x7a, 0xe5, 0x67,
	0xe6, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x71, 0x71, 0xc0, 0xcc, 0x93, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0xe5, 0xf9, 0x45, 0xd9, 0x69, 0x39, 0xf9,
	0xe5, 0x12, 0x4c, 0x10, 0x39, 0x18, 0x5f, 0xc9, 0x8f, 0x4b, 0x04, 0x66, 0x9c, 0x4f, 0x6a, 0x62,
	0x59, 0x2a, 0x85, 0xe6, 0x19, 0x4d, 0x60, 0xe4, 0xe2, 0x80, 0x19, 0x28, 0xe4, 0xc0, 0xc5, 0x02,
	0x72, 0xa3, 0x90, 0xac, 0x1e, 0xcc, 0x2f, 0x7a, 0x58, 0xdc, 0x2e, 0x25, 0x8e, 0x90, 0x76, 0xca,
	0x49, 0xcc, 0xcb, 0x0e, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x55, 0x62, 0x10, 0x72, 0xe2,
	0x62, 0x05, 0x3b, 0x4b, 0x48, 0x0e, 0xd3, 0x08, 0x64, 0xf7, 0xe2, 0x31, 0x23, 0x89, 0x0d, 0x1c,
	0x70, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0xa8, 0x46, 0x19, 0x80, 0x01, 0x00, 0x00,
}
