// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/approval/shared.proto

package approval

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 工作流模式
type WorkflowMode int32

const (
	WorkflowMode_WORKFLOW_MODE_INVALID  WorkflowMode = 0
	WorkflowMode_WORKFLOW_MODE_ALL      WorkflowMode = 1
	WorkflowMode_WORKFLOW_MODE_ANY      WorkflowMode = 2
	WorkflowMode_WORKFLOW_MODE_MAJORITY WorkflowMode = 3
)

var WorkflowMode_name = map[int32]string{
	0: "WORKFLOW_MODE_INVALID",
	1: "WORKFLOW_MODE_ALL",
	2: "WORKFLOW_MODE_ANY",
	3: "WORKFLOW_MODE_MAJORITY",
}

var WorkflowMode_value = map[string]int32{
	"WORKFLOW_MODE_INVALID":  0,
	"WORKFLOW_MODE_ALL":      1,
	"WORKFLOW_MODE_ANY":      2,
	"WORKFLOW_MODE_MAJORITY": 3,
}

func (x WorkflowMode) String() string {
	return proto.EnumName(WorkflowMode_name, int32(x))
}

func (WorkflowMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aaa2e0860ed5e576, []int{0}
}

// 任务状态
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_INVALID  TaskStatus = 0
	TaskStatus_TASK_STATUS_PENDING  TaskStatus = 1
	TaskStatus_TASK_STATUS_ACCEPTED TaskStatus = 2
	TaskStatus_TASK_STATUS_REJECTED TaskStatus = 3
)

var TaskStatus_name = map[int32]string{
	0: "TASK_STATUS_INVALID",
	1: "TASK_STATUS_PENDING",
	2: "TASK_STATUS_ACCEPTED",
	3: "TASK_STATUS_REJECTED",
}

var TaskStatus_value = map[string]int32{
	"TASK_STATUS_INVALID":  0,
	"TASK_STATUS_PENDING":  1,
	"TASK_STATUS_ACCEPTED": 2,
	"TASK_STATUS_REJECTED": 3,
}

func (x TaskStatus) String() string {
	return proto.EnumName(TaskStatus_name, int32(x))
}

func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aaa2e0860ed5e576, []int{1}
}

// 记录状态
type ActionStatus int32

const (
	ActionStatus_ACTION_STATUS_INVALID  ActionStatus = 0
	ActionStatus_ACTION_STATUS_ACCEPTED ActionStatus = 1
	ActionStatus_ACTION_STATUS_REJECTED ActionStatus = 2
)

var ActionStatus_name = map[int32]string{
	0: "ACTION_STATUS_INVALID",
	1: "ACTION_STATUS_ACCEPTED",
	2: "ACTION_STATUS_REJECTED",
}

var ActionStatus_value = map[string]int32{
	"ACTION_STATUS_INVALID":  0,
	"ACTION_STATUS_ACCEPTED": 1,
	"ACTION_STATUS_REJECTED": 2,
}

func (x ActionStatus) String() string {
	return proto.EnumName(ActionStatus_name, int32(x))
}

func (ActionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aaa2e0860ed5e576, []int{2}
}

// 状态
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa2e0860ed5e576, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 空白请求
type BlankRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlankRequest) Reset()         { *m = BlankRequest{} }
func (m *BlankRequest) String() string { return proto.CompactTextString(m) }
func (*BlankRequest) ProtoMessage()    {}
func (*BlankRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa2e0860ed5e576, []int{1}
}

func (m *BlankRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlankRequest.Unmarshal(m, b)
}
func (m *BlankRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlankRequest.Marshal(b, m, deterministic)
}
func (m *BlankRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlankRequest.Merge(m, src)
}
func (m *BlankRequest) XXX_Size() int {
	return xxx_messageInfo_BlankRequest.Size(m)
}
func (m *BlankRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlankRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlankRequest proto.InternalMessageInfo

// 空白回复
type BlankResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlankResponse) Reset()         { *m = BlankResponse{} }
func (m *BlankResponse) String() string { return proto.CompactTextString(m) }
func (*BlankResponse) ProtoMessage()    {}
func (*BlankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa2e0860ed5e576, []int{2}
}

func (m *BlankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlankResponse.Unmarshal(m, b)
}
func (m *BlankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlankResponse.Marshal(b, m, deterministic)
}
func (m *BlankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlankResponse.Merge(m, src)
}
func (m *BlankResponse) XXX_Size() int {
	return xxx_messageInfo_BlankResponse.Size(m)
}
func (m *BlankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlankResponse proto.InternalMessageInfo

func (m *BlankResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// 工作流实体
type WorkflowEntity struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode                 WorkflowMode `protobuf:"varint,3,opt,name=mode,proto3,enum=approval.WorkflowMode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WorkflowEntity) Reset()         { *m = WorkflowEntity{} }
func (m *WorkflowEntity) String() string { return proto.CompactTextString(m) }
func (*WorkflowEntity) ProtoMessage()    {}
func (*WorkflowEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa2e0860ed5e576, []int{3}
}

func (m *WorkflowEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowEntity.Unmarshal(m, b)
}
func (m *WorkflowEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowEntity.Marshal(b, m, deterministic)
}
func (m *WorkflowEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowEntity.Merge(m, src)
}
func (m *WorkflowEntity) XXX_Size() int {
	return xxx_messageInfo_WorkflowEntity.Size(m)
}
func (m *WorkflowEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowEntity.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowEntity proto.InternalMessageInfo

func (m *WorkflowEntity) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *WorkflowEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowEntity) GetMode() WorkflowMode {
	if m != nil {
		return m.Mode
	}
	return WorkflowMode_WORKFLOW_MODE_INVALID
}

// 任务实体
type TaskEntity struct {
	Uuid                 string     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Subject              string     `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 string     `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Meta                 string     `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	State                TaskStatus `protobuf:"varint,5,opt,name=state,proto3,enum=approval.TaskStatus" json:"state,omitempty"`
	Workflow             string     `protobuf:"bytes,6,opt,name=workflow,proto3" json:"workflow,omitempty"`
	UpdatedAt            int64      `protobuf:"varint,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TaskEntity) Reset()         { *m = TaskEntity{} }
func (m *TaskEntity) String() string { return proto.CompactTextString(m) }
func (*TaskEntity) ProtoMessage()    {}
func (*TaskEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa2e0860ed5e576, []int{4}
}

func (m *TaskEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskEntity.Unmarshal(m, b)
}
func (m *TaskEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskEntity.Marshal(b, m, deterministic)
}
func (m *TaskEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskEntity.Merge(m, src)
}
func (m *TaskEntity) XXX_Size() int {
	return xxx_messageInfo_TaskEntity.Size(m)
}
func (m *TaskEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskEntity.DiscardUnknown(m)
}

var xxx_messageInfo_TaskEntity proto.InternalMessageInfo

func (m *TaskEntity) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TaskEntity) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *TaskEntity) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *TaskEntity) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *TaskEntity) GetState() TaskStatus {
	if m != nil {
		return m.State
	}
	return TaskStatus_TASK_STATUS_INVALID
}

func (m *TaskEntity) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *TaskEntity) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// 记录实体
type ActionEntity struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Task                 string       `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Operator             string       `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	State                ActionStatus `protobuf:"varint,4,opt,name=state,proto3,enum=approval.ActionStatus" json:"state,omitempty"`
	Reason               string       `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	UpdatedAt            int64        `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ActionEntity) Reset()         { *m = ActionEntity{} }
func (m *ActionEntity) String() string { return proto.CompactTextString(m) }
func (*ActionEntity) ProtoMessage()    {}
func (*ActionEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa2e0860ed5e576, []int{5}
}

func (m *ActionEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionEntity.Unmarshal(m, b)
}
func (m *ActionEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionEntity.Marshal(b, m, deterministic)
}
func (m *ActionEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionEntity.Merge(m, src)
}
func (m *ActionEntity) XXX_Size() int {
	return xxx_messageInfo_ActionEntity.Size(m)
}
func (m *ActionEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionEntity.DiscardUnknown(m)
}

var xxx_messageInfo_ActionEntity proto.InternalMessageInfo

func (m *ActionEntity) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ActionEntity) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

func (m *ActionEntity) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ActionEntity) GetState() ActionStatus {
	if m != nil {
		return m.State
	}
	return ActionStatus_ACTION_STATUS_INVALID
}

func (m *ActionEntity) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *ActionEntity) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("approval.WorkflowMode", WorkflowMode_name, WorkflowMode_value)
	proto.RegisterEnum("approval.TaskStatus", TaskStatus_name, TaskStatus_value)
	proto.RegisterEnum("approval.ActionStatus", ActionStatus_name, ActionStatus_value)
	proto.RegisterType((*Status)(nil), "approval.Status")
	proto.RegisterType((*BlankRequest)(nil), "approval.BlankRequest")
	proto.RegisterType((*BlankResponse)(nil), "approval.BlankResponse")
	proto.RegisterType((*WorkflowEntity)(nil), "approval.WorkflowEntity")
	proto.RegisterType((*TaskEntity)(nil), "approval.TaskEntity")
	proto.RegisterType((*ActionEntity)(nil), "approval.ActionEntity")
}

func init() {
	proto.RegisterFile("proto/approval/shared.proto", fileDescriptor_aaa2e0860ed5e576)
}

var fileDescriptor_aaa2e0860ed5e576 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x5d, 0x6f, 0xda, 0x3e,
	0x14, 0xc6, 0xff, 0xe6, 0x25, 0x94, 0xf3, 0x67, 0x28, 0xf3, 0x0a, 0x4b, 0xd9, 0x2e, 0x50, 0xae,
	0x10, 0x9a, 0xa8, 0xd4, 0x49, 0x93, 0x76, 0x99, 0x41, 0x36, 0xd1, 0xf2, 0x52, 0x99, 0x6c, 0xa8,
	0x57, 0xc8, 0x10, 0x6f, 0x63, 0x40, 0x9c, 0xc5, 0xce, 0xaa, 0x7e, 0xb1, 0x7d, 0x86, 0x7d, 0xac,
	0xc9, 0x4e, 0x02, 0x84, 0x4e, 0xbd, 0x3b, 0xe7, 0x79, 0xcc, 0xf9, 0x3d, 0xc7, 0x26, 0xf0, 0x2a,
	0x8c, 0xb8, 0xe4, 0x97, 0x34, 0x0c, 0x23, 0xfe, 0x8b, 0x6e, 0x2f, 0xc5, 0x77, 0x1a, 0x31, 0xbf,
	0xa7, 0x55, 0x7c, 0x96, 0xc9, 0xf6, 0x3b, 0x30, 0x66, 0x92, 0xca, 0x58, 0x60, 0x0c, 0xa5, 0x15,
	0xf7, 0x99, 0x85, 0xda, 0xa8, 0x53, 0x26, 0xba, 0xc6, 0x16, 0x54, 0x76, 0x4c, 0x08, 0xfa, 0x8d,
	0x59, 0x85, 0x36, 0xea, 0x54, 0x49, 0xd6, 0xda, 0x75, 0xa8, 0x7d, 0xd8, 0xd2, 0x60, 0x43, 0xd8,
	0xcf, 0x98, 0x09, 0x69, 0xbf, 0x87, 0x67, 0x69, 0x2f, 0x42, 0x1e, 0x08, 0x86, 0x3b, 0x60, 0x08,
	0x3d, 0x58, 0x0f, 0xfc, 0xff, 0xca, 0xec, 0x65, 0xcc, 0x5e, 0x02, 0x24, 0xa9, 0x6f, 0xfb, 0x50,
	0x9f, 0xf3, 0x68, 0xf3, 0x75, 0xcb, 0xef, 0xdd, 0x40, 0xae, 0xe5, 0x83, 0x8a, 0x12, 0xc7, 0x6b,
	0x5f, 0xff, 0xb2, 0x4a, 0x74, 0xad, 0xb4, 0x80, 0xee, 0xb2, 0x1c, 0xba, 0xc6, 0x5d, 0x28, 0xed,
	0x54, 0xe4, 0x62, 0x1b, 0x75, 0xea, 0x57, 0xcd, 0x03, 0x21, 0x9b, 0x37, 0xe6, 0x3e, 0x23, 0xfa,
	0x8c, 0xfd, 0x07, 0x01, 0x78, 0x54, 0x6c, 0x9e, 0x40, 0x58, 0x50, 0x11, 0xf1, 0xf2, 0x07, 0x5b,
	0xc9, 0x6c, 0xdb, 0xb4, 0x55, 0xa7, 0x97, 0xdc, 0x7f, 0xd0, 0xa0, 0x2a, 0xd1, 0xb5, 0xd2, 0x76,
	0x4c, 0x52, 0xab, 0x94, 0x68, 0xaa, 0xc6, 0x5d, 0x28, 0xab, 0xa5, 0x98, 0x55, 0xd6, 0x89, 0xce,
	0x0f, 0x89, 0x14, 0x3a, 0xdd, 0x3b, 0x39, 0x82, 0x5b, 0x70, 0x76, 0x9f, 0xc6, 0xb4, 0x0c, 0x3d,
	0x63, 0xdf, 0xe3, 0xd7, 0x50, 0x8d, 0x43, 0x9f, 0x4a, 0xe6, 0x3b, 0xd2, 0xaa, 0xb4, 0x51, 0xa7,
	0x48, 0x0e, 0x82, 0xfd, 0x1b, 0x41, 0xcd, 0x59, 0xc9, 0x35, 0x0f, 0x9e, 0xbe, 0x2f, 0x49, 0xc5,
	0x26, 0xbb, 0x2f, 0x55, 0x2b, 0x24, 0x0f, 0x59, 0x44, 0x25, 0x8f, 0xd2, 0x55, 0xf6, 0x3d, 0x7e,
	0x93, 0x45, 0x2f, 0x9d, 0x5e, 0x66, 0x82, 0xca, 0x87, 0x6f, 0x82, 0x11, 0x31, 0x2a, 0x78, 0xa0,
	0x37, 0xad, 0x92, 0xb4, 0xcb, 0x07, 0x37, 0x4e, 0x82, 0x77, 0x05, 0xd4, 0x8e, 0x5f, 0x06, 0x5f,
	0x40, 0x63, 0x3e, 0x25, 0x37, 0x1f, 0x47, 0xd3, 0xf9, 0x62, 0x3c, 0x1d, 0xb8, 0x8b, 0xe1, 0xe4,
	0x8b, 0x33, 0x1a, 0x0e, 0xcc, 0xff, 0x70, 0x03, 0x9e, 0xe7, 0x2d, 0x67, 0x34, 0x32, 0xd1, 0x3f,
	0xe4, 0xc9, 0x9d, 0x59, 0xc0, 0x2d, 0x68, 0xe6, 0xe5, 0xb1, 0x73, 0x3d, 0x25, 0x43, 0xef, 0xce,
	0x2c, 0x76, 0xa3, 0xe4, 0xdd, 0xd3, 0x7f, 0xf9, 0x4b, 0x78, 0xe1, 0x39, 0xb3, 0x9b, 0xc5, 0xcc,
	0x73, 0xbc, 0xcf, 0xb3, 0x23, 0xe0, 0x89, 0x71, 0xeb, 0x4e, 0x06, 0xc3, 0xc9, 0x27, 0x13, 0x61,
	0x0b, 0xce, 0x8f, 0x0d, 0xa7, 0xdf, 0x77, 0x6f, 0x3d, 0x77, 0x60, 0x16, 0x4e, 0x1d, 0xe2, 0x5e,
	0xbb, 0x7d, 0xe5, 0x14, 0xbb, 0x34, 0x7b, 0xa0, 0x94, 0x7a, 0x01, 0x0d, 0xa7, 0xef, 0x0d, 0xa7,
	0x93, 0xc7, 0xdc, 0x16, 0x34, 0xf3, 0xd6, 0x1e, 0x80, 0x1e, 0x7b, 0x7b, 0x44, 0x61, 0x69, 0xe8,
	0x2f, 0xf9, 0xed, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x89, 0xc5, 0x64, 0xe8, 0x03, 0x00,
	0x00,
}
