// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/approval/task.proto

package approval

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 提交的请求
type TaskSubmitRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Workflow             string   `protobuf:"bytes,3,opt,name=workflow,proto3" json:"workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskSubmitRequest) Reset()         { *m = TaskSubmitRequest{} }
func (m *TaskSubmitRequest) String() string { return proto.CompactTextString(m) }
func (*TaskSubmitRequest) ProtoMessage()    {}
func (*TaskSubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7f6fd089d79f2ee, []int{0}
}

func (m *TaskSubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskSubmitRequest.Unmarshal(m, b)
}
func (m *TaskSubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskSubmitRequest.Marshal(b, m, deterministic)
}
func (m *TaskSubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskSubmitRequest.Merge(m, src)
}
func (m *TaskSubmitRequest) XXX_Size() int {
	return xxx_messageInfo_TaskSubmitRequest.Size(m)
}
func (m *TaskSubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskSubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskSubmitRequest proto.InternalMessageInfo

func (m *TaskSubmitRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *TaskSubmitRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *TaskSubmitRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

// 通过的请求
type TaskAcceptRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskAcceptRequest) Reset()         { *m = TaskAcceptRequest{} }
func (m *TaskAcceptRequest) String() string { return proto.CompactTextString(m) }
func (*TaskAcceptRequest) ProtoMessage()    {}
func (*TaskAcceptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7f6fd089d79f2ee, []int{1}
}

func (m *TaskAcceptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskAcceptRequest.Unmarshal(m, b)
}
func (m *TaskAcceptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskAcceptRequest.Marshal(b, m, deterministic)
}
func (m *TaskAcceptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskAcceptRequest.Merge(m, src)
}
func (m *TaskAcceptRequest) XXX_Size() int {
	return xxx_messageInfo_TaskAcceptRequest.Size(m)
}
func (m *TaskAcceptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskAcceptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskAcceptRequest proto.InternalMessageInfo

func (m *TaskAcceptRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TaskAcceptRequest) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

// 驳回的请求
type TaskRejectRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRejectRequest) Reset()         { *m = TaskRejectRequest{} }
func (m *TaskRejectRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRejectRequest) ProtoMessage()    {}
func (*TaskRejectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7f6fd089d79f2ee, []int{2}
}

func (m *TaskRejectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRejectRequest.Unmarshal(m, b)
}
func (m *TaskRejectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRejectRequest.Marshal(b, m, deterministic)
}
func (m *TaskRejectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRejectRequest.Merge(m, src)
}
func (m *TaskRejectRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRejectRequest.Size(m)
}
func (m *TaskRejectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRejectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRejectRequest proto.InternalMessageInfo

func (m *TaskRejectRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TaskRejectRequest) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

// 获取的请求
type TaskGetRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskGetRequest) Reset()         { *m = TaskGetRequest{} }
func (m *TaskGetRequest) String() string { return proto.CompactTextString(m) }
func (*TaskGetRequest) ProtoMessage()    {}
func (*TaskGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7f6fd089d79f2ee, []int{3}
}

func (m *TaskGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskGetRequest.Unmarshal(m, b)
}
func (m *TaskGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskGetRequest.Marshal(b, m, deterministic)
}
func (m *TaskGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskGetRequest.Merge(m, src)
}
func (m *TaskGetRequest) XXX_Size() int {
	return xxx_messageInfo_TaskGetRequest.Size(m)
}
func (m *TaskGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskGetRequest proto.InternalMessageInfo

func (m *TaskGetRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// 获取的回复
type TaskGetResponse struct {
	Status               *Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Entity               *TaskEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TaskGetResponse) Reset()         { *m = TaskGetResponse{} }
func (m *TaskGetResponse) String() string { return proto.CompactTextString(m) }
func (*TaskGetResponse) ProtoMessage()    {}
func (*TaskGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7f6fd089d79f2ee, []int{4}
}

func (m *TaskGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskGetResponse.Unmarshal(m, b)
}
func (m *TaskGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskGetResponse.Marshal(b, m, deterministic)
}
func (m *TaskGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskGetResponse.Merge(m, src)
}
func (m *TaskGetResponse) XXX_Size() int {
	return xxx_messageInfo_TaskGetResponse.Size(m)
}
func (m *TaskGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskGetResponse proto.InternalMessageInfo

func (m *TaskGetResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *TaskGetResponse) GetEntity() *TaskEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

// 列举的请求
type TaskListRequest struct {
	Offset               int64      `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Workflow             string     `protobuf:"bytes,3,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Opreator             string     `protobuf:"bytes,4,opt,name=opreator,proto3" json:"opreator,omitempty"`
	State                TaskStatus `protobuf:"varint,5,opt,name=state,proto3,enum=approval.TaskStatus" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TaskListRequest) Reset()         { *m = TaskListRequest{} }
func (m *TaskListRequest) String() string { return proto.CompactTextString(m) }
func (*TaskListRequest) ProtoMessage()    {}
func (*TaskListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7f6fd089d79f2ee, []int{5}
}

func (m *TaskListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskListRequest.Unmarshal(m, b)
}
func (m *TaskListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskListRequest.Marshal(b, m, deterministic)
}
func (m *TaskListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskListRequest.Merge(m, src)
}
func (m *TaskListRequest) XXX_Size() int {
	return xxx_messageInfo_TaskListRequest.Size(m)
}
func (m *TaskListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskListRequest proto.InternalMessageInfo

func (m *TaskListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *TaskListRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *TaskListRequest) GetWorkflow() string {
	if m != nil {
		return m.Workflow
	}
	return ""
}

func (m *TaskListRequest) GetOpreator() string {
	if m != nil {
		return m.Opreator
	}
	return ""
}

func (m *TaskListRequest) GetState() TaskStatus {
	if m != nil {
		return m.State
	}
	return TaskStatus_TASK_STATUS_INVALID
}

// 列举的回复
type TaskListResponse struct {
	Status               *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint64        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*TaskEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TaskListResponse) Reset()         { *m = TaskListResponse{} }
func (m *TaskListResponse) String() string { return proto.CompactTextString(m) }
func (*TaskListResponse) ProtoMessage()    {}
func (*TaskListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7f6fd089d79f2ee, []int{6}
}

func (m *TaskListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskListResponse.Unmarshal(m, b)
}
func (m *TaskListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskListResponse.Marshal(b, m, deterministic)
}
func (m *TaskListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskListResponse.Merge(m, src)
}
func (m *TaskListResponse) XXX_Size() int {
	return xxx_messageInfo_TaskListResponse.Size(m)
}
func (m *TaskListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskListResponse proto.InternalMessageInfo

func (m *TaskListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *TaskListResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *TaskListResponse) GetEntity() []*TaskEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskSubmitRequest)(nil), "approval.TaskSubmitRequest")
	proto.RegisterType((*TaskAcceptRequest)(nil), "approval.TaskAcceptRequest")
	proto.RegisterType((*TaskRejectRequest)(nil), "approval.TaskRejectRequest")
	proto.RegisterType((*TaskGetRequest)(nil), "approval.TaskGetRequest")
	proto.RegisterType((*TaskGetResponse)(nil), "approval.TaskGetResponse")
	proto.RegisterType((*TaskListRequest)(nil), "approval.TaskListRequest")
	proto.RegisterType((*TaskListResponse)(nil), "approval.TaskListResponse")
}

func init() {
	proto.RegisterFile("proto/approval/task.proto", fileDescriptor_c7f6fd089d79f2ee)
}

var fileDescriptor_c7f6fd089d79f2ee = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcb, 0x8e, 0xda, 0x30,
	0x18, 0x85, 0x09, 0xb9, 0x94, 0xfe, 0x48, 0x94, 0x5a, 0xa8, 0x0d, 0x61, 0x83, 0xa2, 0x2e, 0x50,
	0x55, 0x81, 0x44, 0xb7, 0x55, 0xd5, 0x8b, 0x2a, 0x36, 0x5d, 0x99, 0x6e, 0xbb, 0x70, 0x82, 0x51,
	0xd3, 0x64, 0xe2, 0x4c, 0xec, 0x0c, 0x9a, 0xdd, 0xbc, 0xcb, 0xbc, 0xcd, 0x3c, 0xd5, 0xc8, 0x76,
	0x2e, 0x24, 0x1a, 0x05, 0xcd, 0xec, 0xfc, 0x5f, 0xfc, 0x71, 0x38, 0x3e, 0x81, 0x79, 0x96, 0x33,
	0xc1, 0x36, 0x24, 0xcb, 0x72, 0x76, 0x43, 0x92, 0x8d, 0x20, 0x3c, 0x5e, 0xab, 0x1e, 0x1a, 0x55,
	0x4d, 0x6f, 0xd1, 0x59, 0xe2, 0xff, 0x48, 0x4e, 0x0f, 0x7a, 0xcd, 0xff, 0x0b, 0x6f, 0xff, 0x10,
	0x1e, 0xef, 0x8b, 0xe0, 0x2a, 0x12, 0x98, 0x5e, 0x17, 0x94, 0x0b, 0xe4, 0xc2, 0x2b, 0x5e, 0x04,
	0xff, 0x69, 0x28, 0x5c, 0x63, 0x69, 0xac, 0x5e, 0xe3, 0xaa, 0x44, 0x08, 0xac, 0x80, 0x1d, 0x6e,
	0xdd, 0xa1, 0x6a, 0xab, 0x33, 0xf2, 0x60, 0x74, 0x62, 0x79, 0x7c, 0x4c, 0xd8, 0xc9, 0x35, 0x55,
	0xbf, 0xae, 0xfd, 0x9f, 0x1a, 0xff, 0x3d, 0x0c, 0x69, 0x56, 0xe3, 0x11, 0x58, 0x45, 0x11, 0x1d,
	0x4a, 0xb6, 0x3a, 0x4b, 0x08, 0xcb, 0x68, 0x4e, 0x04, 0xcb, 0x4b, 0x78, 0x5d, 0x57, 0x10, 0x4c,
	0xa5, 0x84, 0x97, 0x42, 0x3e, 0xc0, 0x44, 0x42, 0x76, 0xb4, 0x8f, 0xe0, 0x47, 0xf0, 0xa6, 0xde,
	0xe2, 0x19, 0x4b, 0x39, 0x45, 0x2b, 0x70, 0xb8, 0x20, 0xa2, 0xe0, 0x6a, 0x71, 0xbc, 0x9d, 0xae,
	0x2b, 0x27, 0xd7, 0x7b, 0xd5, 0xc7, 0xe5, 0x1c, 0x7d, 0x02, 0x87, 0xa6, 0x22, 0x12, 0xda, 0x9e,
	0xf1, 0x76, 0xd6, 0x6c, 0x4a, 0xe8, 0x2f, 0x35, 0xc3, 0xe5, 0x8e, 0x7f, 0x6f, 0xe8, 0xdf, 0xfa,
	0x1d, 0xf1, 0x5a, 0xd2, 0x3b, 0x70, 0xd8, 0xf1, 0xc8, 0xa9, 0xf6, 0xdd, 0xc4, 0x65, 0x85, 0x66,
	0x60, 0x87, 0xac, 0x48, 0x85, 0x02, 0x9b, 0x58, 0x17, 0x7d, 0xc6, 0x6b, 0x2b, 0x72, 0xaa, 0xac,
	0xb0, 0x2a, 0x2b, 0x74, 0x8d, 0x3e, 0x82, 0x2d, 0x15, 0x53, 0xd7, 0x5e, 0x1a, 0xab, 0x49, 0x57,
	0x66, 0xf9, 0xa7, 0xf4, 0x8a, 0x7f, 0x67, 0xc0, 0xb4, 0x51, 0xf9, 0x6c, 0x4b, 0x66, 0x60, 0x0b,
	0x26, 0x48, 0xa2, 0x84, 0x5b, 0x58, 0x17, 0x67, 0x46, 0x99, 0x4b, 0xf3, 0x92, 0x51, 0xdb, 0x87,
	0x21, 0x58, 0xb2, 0x8d, 0xbe, 0x81, 0xa3, 0x73, 0x8a, 0x16, 0x1d, 0xc9, 0xe7, 0xe9, 0xf5, 0xde,
	0x37, 0xc3, 0x1f, 0x09, 0x49, 0xe3, 0x4a, 0xb6, 0x3f, 0x90, 0x04, 0x1d, 0xc5, 0x2e, 0xa1, 0x15,
	0xd0, 0x0b, 0x04, 0x9d, 0xc3, 0x2e, 0xa1, 0x95, 0xce, 0x3e, 0xc2, 0x17, 0x30, 0x77, 0x54, 0x20,
	0xb7, 0x7d, 0xbd, 0xc9, 0xa5, 0x37, 0x7f, 0x62, 0x52, 0xdf, 0xfe, 0x0a, 0x96, 0x7c, 0x8a, 0x9e,
	0xeb, 0x5e, 0x7b, 0x72, 0xfe, 0x70, 0xfe, 0x20, 0x70, 0xd4, 0x67, 0xff, 0xf9, 0x31, 0x00, 0x00,
	0xff, 0xff, 0xd5, 0xb8, 0x95, 0x91, 0x3a, 0x04, 0x00, 0x00,
}
