// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/approval/workflow.proto

package approval

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 创建的请求
type WorkflowMakeRequest struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode                 WorkflowMode `protobuf:"varint,2,opt,name=mode,proto3,enum=approval.WorkflowMode" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WorkflowMakeRequest) Reset()         { *m = WorkflowMakeRequest{} }
func (m *WorkflowMakeRequest) String() string { return proto.CompactTextString(m) }
func (*WorkflowMakeRequest) ProtoMessage()    {}
func (*WorkflowMakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_823b1463671f157d, []int{0}
}

func (m *WorkflowMakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowMakeRequest.Unmarshal(m, b)
}
func (m *WorkflowMakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowMakeRequest.Marshal(b, m, deterministic)
}
func (m *WorkflowMakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowMakeRequest.Merge(m, src)
}
func (m *WorkflowMakeRequest) XXX_Size() int {
	return xxx_messageInfo_WorkflowMakeRequest.Size(m)
}
func (m *WorkflowMakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowMakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowMakeRequest proto.InternalMessageInfo

func (m *WorkflowMakeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowMakeRequest) GetMode() WorkflowMode {
	if m != nil {
		return m.Mode
	}
	return WorkflowMode_WORKFLOW_MODE_INVALID
}

// 列举的请求
type WorkflowListRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowListRequest) Reset()         { *m = WorkflowListRequest{} }
func (m *WorkflowListRequest) String() string { return proto.CompactTextString(m) }
func (*WorkflowListRequest) ProtoMessage()    {}
func (*WorkflowListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_823b1463671f157d, []int{1}
}

func (m *WorkflowListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowListRequest.Unmarshal(m, b)
}
func (m *WorkflowListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowListRequest.Marshal(b, m, deterministic)
}
func (m *WorkflowListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowListRequest.Merge(m, src)
}
func (m *WorkflowListRequest) XXX_Size() int {
	return xxx_messageInfo_WorkflowListRequest.Size(m)
}
func (m *WorkflowListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowListRequest proto.InternalMessageInfo

func (m *WorkflowListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *WorkflowListRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 列举的回复
type WorkflowListResponse struct {
	Status               *Status           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint64            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*WorkflowEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WorkflowListResponse) Reset()         { *m = WorkflowListResponse{} }
func (m *WorkflowListResponse) String() string { return proto.CompactTextString(m) }
func (*WorkflowListResponse) ProtoMessage()    {}
func (*WorkflowListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_823b1463671f157d, []int{2}
}

func (m *WorkflowListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowListResponse.Unmarshal(m, b)
}
func (m *WorkflowListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowListResponse.Marshal(b, m, deterministic)
}
func (m *WorkflowListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowListResponse.Merge(m, src)
}
func (m *WorkflowListResponse) XXX_Size() int {
	return xxx_messageInfo_WorkflowListResponse.Size(m)
}
func (m *WorkflowListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowListResponse proto.InternalMessageInfo

func (m *WorkflowListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *WorkflowListResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *WorkflowListResponse) GetEntity() []*WorkflowEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

// 删除的请求
type WorkflowRemoveRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowRemoveRequest) Reset()         { *m = WorkflowRemoveRequest{} }
func (m *WorkflowRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*WorkflowRemoveRequest) ProtoMessage()    {}
func (*WorkflowRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_823b1463671f157d, []int{3}
}

func (m *WorkflowRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowRemoveRequest.Unmarshal(m, b)
}
func (m *WorkflowRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowRemoveRequest.Marshal(b, m, deterministic)
}
func (m *WorkflowRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowRemoveRequest.Merge(m, src)
}
func (m *WorkflowRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_WorkflowRemoveRequest.Size(m)
}
func (m *WorkflowRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowRemoveRequest proto.InternalMessageInfo

func (m *WorkflowRemoveRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// 获取的请求
type WorkflowGetRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkflowGetRequest) Reset()         { *m = WorkflowGetRequest{} }
func (m *WorkflowGetRequest) String() string { return proto.CompactTextString(m) }
func (*WorkflowGetRequest) ProtoMessage()    {}
func (*WorkflowGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_823b1463671f157d, []int{4}
}

func (m *WorkflowGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowGetRequest.Unmarshal(m, b)
}
func (m *WorkflowGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowGetRequest.Marshal(b, m, deterministic)
}
func (m *WorkflowGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowGetRequest.Merge(m, src)
}
func (m *WorkflowGetRequest) XXX_Size() int {
	return xxx_messageInfo_WorkflowGetRequest.Size(m)
}
func (m *WorkflowGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowGetRequest proto.InternalMessageInfo

func (m *WorkflowGetRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *WorkflowGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 获取的回复
type WorkflowGetResponse struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Entity               *WorkflowEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WorkflowGetResponse) Reset()         { *m = WorkflowGetResponse{} }
func (m *WorkflowGetResponse) String() string { return proto.CompactTextString(m) }
func (*WorkflowGetResponse) ProtoMessage()    {}
func (*WorkflowGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_823b1463671f157d, []int{5}
}

func (m *WorkflowGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowGetResponse.Unmarshal(m, b)
}
func (m *WorkflowGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowGetResponse.Marshal(b, m, deterministic)
}
func (m *WorkflowGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowGetResponse.Merge(m, src)
}
func (m *WorkflowGetResponse) XXX_Size() int {
	return xxx_messageInfo_WorkflowGetResponse.Size(m)
}
func (m *WorkflowGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowGetResponse proto.InternalMessageInfo

func (m *WorkflowGetResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *WorkflowGetResponse) GetEntity() *WorkflowEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*WorkflowMakeRequest)(nil), "approval.WorkflowMakeRequest")
	proto.RegisterType((*WorkflowListRequest)(nil), "approval.WorkflowListRequest")
	proto.RegisterType((*WorkflowListResponse)(nil), "approval.WorkflowListResponse")
	proto.RegisterType((*WorkflowRemoveRequest)(nil), "approval.WorkflowRemoveRequest")
	proto.RegisterType((*WorkflowGetRequest)(nil), "approval.WorkflowGetRequest")
	proto.RegisterType((*WorkflowGetResponse)(nil), "approval.WorkflowGetResponse")
}

func init() {
	proto.RegisterFile("proto/approval/workflow.proto", fileDescriptor_823b1463671f157d)
}

var fileDescriptor_823b1463671f157d = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdf, 0x4e, 0xc2, 0x30,
	0x14, 0xc6, 0xdd, 0x1f, 0x17, 0x3c, 0x24, 0xc6, 0x54, 0xc4, 0x65, 0x8a, 0x92, 0x5d, 0x2d, 0x9a,
	0x80, 0x99, 0xb7, 0x5e, 0x18, 0xc5, 0x70, 0xa3, 0x37, 0x35, 0xc6, 0xeb, 0xea, 0x4a, 0x24, 0x8c,
	0x75, 0xac, 0x1d, 0xc4, 0x37, 0xf0, 0x35, 0x7c, 0x53, 0xb3, 0x6e, 0xa5, 0x20, 0x7f, 0x8c, 0x77,
	0x6b, 0xbf, 0xaf, 0xbf, 0x9c, 0xf3, 0x9d, 0x33, 0x68, 0xa5, 0x19, 0x13, 0xac, 0x4b, 0xd2, 0x34,
	0x63, 0x53, 0x12, 0x77, 0x67, 0x2c, 0x1b, 0x0d, 0x62, 0x36, 0xeb, 0xc8, 0x7b, 0x54, 0x53, 0x82,
	0x77, 0xf2, 0xcb, 0xc8, 0x3f, 0x48, 0x46, 0xa3, 0xd2, 0xe6, 0xbf, 0xc0, 0xe1, 0x6b, 0xf5, 0xf0,
	0x89, 0x8c, 0x28, 0xa6, 0x93, 0x9c, 0x72, 0x81, 0x10, 0xd8, 0x09, 0x19, 0x53, 0xd7, 0x68, 0x1b,
	0xc1, 0x1e, 0x96, 0xdf, 0xe8, 0x02, 0xec, 0x31, 0x8b, 0xa8, 0x6b, 0xb6, 0x8d, 0x60, 0x3f, 0x6c,
	0x76, 0x14, 0xb0, 0x33, 0x07, 0xb0, 0x88, 0x62, 0xe9, 0xf1, 0xef, 0x35, 0xf6, 0x71, 0xc8, 0x85,
	0xc2, 0x36, 0xc1, 0x61, 0x83, 0x01, 0xa7, 0x42, 0x82, 0x2d, 0x5c, 0x9d, 0x50, 0x03, 0x76, 0xdf,
	0x59, 0x9e, 0x08, 0xc9, 0xb6, 0x70, 0x79, 0xf0, 0xbf, 0x0c, 0x68, 0x2c, 0x53, 0x78, 0xca, 0x12,
	0x4e, 0x51, 0x00, 0x0e, 0x17, 0x44, 0xe4, 0x5c, 0x62, 0xea, 0xe1, 0x81, 0xae, 0xe5, 0x59, 0xde,
	0xe3, 0x4a, 0x2f, 0xc0, 0x82, 0x09, 0x12, 0x4b, 0xb0, 0x8d, 0xcb, 0x03, 0xba, 0x02, 0x87, 0x26,
	0x62, 0x28, 0x3e, 0x5d, 0xab, 0x6d, 0x05, 0xf5, 0xd0, 0x5d, 0xed, 0xe5, 0x41, 0xea, 0xb8, 0xf2,
	0xf9, 0x97, 0x70, 0xa4, 0x14, 0x4c, 0xc7, 0x6c, 0xba, 0x18, 0x54, 0x9e, 0x0f, 0x23, 0x15, 0x54,
	0xf1, 0xed, 0xdf, 0x00, 0x52, 0xe6, 0x3e, 0x15, 0x5b, 0x9c, 0xf3, 0x98, 0x4d, 0x1d, 0xb3, 0x3f,
	0xd1, 0xd1, 0xc9, 0xd7, 0xff, 0xee, 0x59, 0x77, 0x67, 0x4a, 0xe7, 0x9f, 0xdd, 0x85, 0xdf, 0x26,
	0xd4, 0x94, 0x84, 0x6e, 0xc1, 0x2e, 0x36, 0x01, 0xb5, 0xd6, 0x0c, 0x58, 0x6f, 0x88, 0x77, 0xac,
	0xe5, 0xbb, 0x98, 0x24, 0x23, 0x55, 0xa8, 0xbf, 0x83, 0xfa, 0x60, 0x17, 0xe3, 0x5a, 0x47, 0x58,
	0x58, 0x06, 0xef, 0x6c, 0x93, 0x3c, 0x07, 0xf5, 0xc0, 0x29, 0xd3, 0x46, 0xe7, 0xab, 0xde, 0xa5,
	0x39, 0x6c, 0x2b, 0xa7, 0x07, 0x56, 0x9f, 0x0a, 0x74, 0xba, 0x8a, 0xd0, 0xd3, 0xf1, 0x5a, 0x1b,
	0x54, 0x45, 0x79, 0x73, 0xe4, 0xff, 0x72, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x08, 0x7d,
	0xae, 0x77, 0x03, 0x00, 0x00,
}
